import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import clsx from "clsx";
import { getServerSession } from "next-auth";
import Provider from "@/components/provider";
import { options } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={clsx(inter.className, "max-w-[600px] mx-auto")}>
        <Provider session={session}>
          <Header />
        </Provider>
        {children}
      </body>
    </html>
  );
}
